ktor:
    application:
        modules:
            - eu.karcags.ceg.ApplicationKt.module
    deployment:
        port: 8080
        auto-reload: false
        development: false
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
